# Generated by Django 3.2.25 on 2024-06-17 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_abbreviation', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('league', models.CharField(blank=True, max_length=100, null=True)),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('arena_name', models.CharField(blank=True, max_length=100, null=True)),
                ('arena_location', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('seating_capacity', models.IntegerField(blank=True, null=True)),
                ('opening_year', models.IntegerField(blank=True, null=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('first_year_of_this_combination', models.IntegerField(blank=True, null=True)),
                ('last_year_of_this_combination', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('equipos', models.ManyToManyField(related_name='ligas', to='tesis.Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias_de_juego', models.CharField(blank=True, default='Lunes, Martes, Miercoles, Jueves, Viernes, Sabado, Domingo', max_length=100, null=True)),
                ('numero_de_juegos', models.IntegerField()),
                ('numero_de_series', models.IntegerField()),
                ('metodo', models.CharField(max_length=100)),
                ('unidad', models.CharField(max_length=100)),
                ('calendario_principal', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torneo_principal', to='tesis.calendario')),
                ('liga', models.ManyToManyField(to='tesis.Liga')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_serie', models.IntegerField()),
                ('calendario', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='series', to='tesis.calendario')),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_inicio', models.DateTimeField()),
                ('fecha_de_fin', models.DateTimeField()),
                ('equipo_en_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_en_casa', to='tesis.equipo')),
                ('equipo_visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_de_visita', to='tesis.equipo')),
                ('serie', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='juegos', to='tesis.serie')),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('poblacion', models.IntegerField()),
                ('generaciones', models.IntegerField()),
                ('probabilidad_de_cruce', models.FloatField()),
                ('probabilidad_de_reproduccion', models.FloatField()),
                ('calendario', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tesis.calendario')),
            ],
        ),
        migrations.CreateModel(
            name='Condicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_condicion', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('calendario', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='condiciones', to='tesis.calendario')),
            ],
        ),
        migrations.AddField(
            model_name='calendario',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesis.torneo'),
        ),
        migrations.AddConstraint(
            model_name='serie',
            constraint=models.UniqueConstraint(fields=('calendario', 'numero_de_serie'), name='unique_serie_per_calendario'),
        ),
    ]
