# Generated by Django 3.2.25 on 2024-07-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='torneo',
            old_name='dias_de_juego',
            new_name='dias_seleccionados',
        ),
    ]
